# Generated by Django 5.1.4 on 2025-01-09 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='organization_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('donor', 'Donor'), ('volunteer', 'Volunteer'), ('non_profit', 'Non-Profit Organization'), ('admin', 'Admin')], max_length=20),
        ),
    ]
